### ISSUE TITLE
[NDTensors] [ENHANCEMENT] Roadmap to removing `TensorStorage` types

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#1250]
Here is a roadmap to removing `TensorStorage` types (`EmptyStorage`, `Dense`, `Diag`, `BlockSparse`, `DiagBlockSparse`, `Combiner`).

### UnallocatedZeros

- [ ] Define `UnallocatedZeros` (in progress in #1213).
- [ ] Use `UnallocatedZeros` as default data type instead of `EmptyStorage` in ITensor constructors.

### DiagonalArray

- [ ] Define `DiagonalArray`.
- [ ] Tensor contraction, addition, QR, eigendecomposition, SVD.
- [ ] Use `DiagonalArray` as default data type instead of `Diag` in ITensor constructors.

### BlockSparse

- [ ] Define `BlockSparseArray`.
- [ ] Tensor contraction, addition, QR, eigendecomposition, SVD.
- [ ] Use `BlockSparseArray` as default data type instead of `BlockSparse` in ITensor QN constructors.

### DiagBlockSparse

- [ ] Use `BlockSparseArray` with blocks storing `DiagonalArray`, make sure all tensor operations work.
- [ ] Replace `DiagBlockSparse` in ITensor QN constructors.

### Combiner

- [ ] Not sure what to do with this, but a lot of functionality will be replaced by the new `fusedims`/`matricize` functionality in `TensorAlgebra`/`BlockSparseArrays` and also by the new `FusionTensor` type.

### Simplify ITensor and Tensor constructors

- [ ] Make ITensor constructors more uniform by using a style `tensor(storage::AbstractArray, inds::Tuple)`, avoid constructors like `DenseTensor`, `DiagTensor`, `BlockSparseTensor`, etc.
- [ ] Use `rand(i, j, k)`, `randn(i, j, k)`, `zeros(i, j, k)`, fill(1.2, i, j, k)`, `diagonal(i, j, k)`, etc. instead of `randomITensor(i, j, k)`, `ITensor(i, j, k)`, `ITensor(1.2, i, j, k)`, `diagonITensor(i, j, k)`.
- [ ] Consider `randn(2, 2)(i, j)` as a shorthand for creating an ITensor with indices `(i, j)` wrapping an array. Also could use `setinds(randn(2, 2), i, j)`.
- [ ] Remove automatic conversion to floating point in ITensor constructor.

### Define `TensorAlgebra` submodule

- [ ] `TensorAlgebra` submodule which defines `contract[!][!]`, `mul[!][!]`, `add[!][!]`, `permutedims[!][!]`, `fusedims`/`matricize`, `contract(::Algorithm"matricize", ...)`, truncated QR, eigendecomposition, SVD, etc. with generic fallback implementations for `AbstractArray` and maybe some specialized implementations for `Array`.

### New `Tensor` semantics

- [ ] Make `Tensor` fully into a wrapper array type with named dimensions, with similar "smart indices" for contraction and addition like the `ITensor` type has right now. Rename to `NamedDimsArray`.
- [ ] Use `struct NamedAxis{Axis,Name} axis::Axis; name::Name; end` as a more generic version of `Index`, where `Index` has a `name` that store the ID, tags, and prime level.

**Comment by mtfishman** [comment]
Related to #1601.
