### ISSUE TITLE
[ITensors] `ITensor` iteration features

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensors.jl#281]
It would be good to define better features for iterating over ITensors and other ITensor objects. For example:

- [x] Define `iterate(::ITensor, ...)` to iterate over all of the elements (both structurally zero and nonzero, for the case of sparse ITensors) (implemented in #457).
- [x] Define `Base.eachindex(A::ITensor)` for ITensors, similar to the Julia version which either outputs a linear index `1:dim(A)` or `CartesianIndices` over `1:dim(A,1),1:dim(A,2),...` depending on the indexing of the ITensor storage (implemented in #457).
- [x] Define `eachindvalset(::IndexSet/ITensor)` that returns an iterator over all `IndexValSet`s (implemented as `eachindval` and `eachval` in #665)
- [ ] Implement functions like [keys](https://docs.julialang.org/en/v1/base/collections/#Base.keys) and [pairs](https://docs.julialang.org/en/v1/base/collections/#Base.pairs) for ITensors for iterating over all `IndexValSet`s and values of the ITensor (a question would be if it should iterate over `IndexValSet` or `CartesianIndex`, both of which would be valid keys of an ITensor).
- [ ] Something like the Julia SparseArrays [findnz](https://docs.julialang.org/en/v1/stdlib/SparseArrays/#SparseArrays.findnz) method for iterating over the nonzero IndeValSets and values of sparse ITensors. This could be split up into `eachnz` to get the elements and `eachnzindval` to get just the non-zero IndexValSets.
- [ ] ~~Define `const IndexValSet{IndexT} = IndexSet{IndexVal{IndexT}}`~~ `IndexSet` was removed in #626 and `IndexVal` was removed in #665, so this would just be a `Tuple{Vararg{Pair{Index}}}`.
