### ISSUE TITLE
Version 0.2 Roadmap

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensors.jl#639]
This issue is to organize what are the minimum changes needed to go to version 0.2. We can include changes that are straightforward and easy to do as well.

- [x] Account for the new Vector storage of IndexSet (closed by #626)
- [x] Make ITensor() default to emptyITensor() #593 (closed by #641)
- [x] Deprecate MPO(A::MPS) constructor in favor of the notation outer(A, A) #581 (closed by #663)
- [x] More general state function #503 (closed by  #664)
- [x] Remove `IndexVal` type in favor of `Pair{<:Index}` (closed by  #665)
- [x] ~~Improve siteinds QN conservation interface #522~~ (Moved to 0.3)
- [x] ~~Make certain delta contractions return views of the original ITensor storage #570~~ (Moved to 0.3)

Feel free to edit, add, remove of course. We may want to save some of the open issues labeled as "breaking" or as 0.2 for future versions, or decide not to make those changes.

**Comment by mtfishman** [comment]
I removed a few that are not breaking and could be done after the release. Also changed those issues to the `v0.3` milestone.

**Comment by emstoudenmire** [comment]
Ok looks like we got these all checked off. Any more breaking changes in the existing PRs or else other issues that would be good to close with 0.2?

**Comment by mtfishman** [comment]
I don't see anything very pressing, I'm ok going ahead with 0.2.

I think the most egregious open issue is #525 (you can see that the polar example is straight up a bug). But since I consider that behavior both buggy and ill-defined, and the `qr` code needs a rewrite and implementation for QN ITensors. `polar` and `qr` aren't currently documented anyway (https://itensor.github.io/ITensors.jl/v0.1/ITensorType.html#Decompositions-1) so we could consider fixing that to be a bug fix in a patch release, or make it a very small 0.3 release.

We should add an "upgrade guide" to the docs with a simple list of breaking changes and common examples of how to upgrade them. Additionally we should point out things that will get deprecated that we plan to remove in future releases, and tell people to run their code with `julia --depwarn=yes` and fix deprecations they see in the warnings.
